[cosmic-ray]
module = "compitum"
module-path = "src"
test-command = "scripts/cr_pytest.cmd"
timeout = 60.0
coverage-file = ".coverage"

excluded-modules = [
    "tests/*",
    "**/__init__.py",
]

[cosmic-ray.distributor]
name = "local"
