<<<<<<< HEAD
[pytest]
markers =
    hypo_lifecycle: marks tests as part of the hypothesis lifecycle suite
=======
[pytest]
markers =
    hypo_lifecycle: marks tests as part of the hypothesis lifecycle suite
>>>>>>> 4d5ca73 (supplementals: initial commit (restore configs, Makefile, benchmarks, examples))
python_functions = test_* benchmark_*